### PR TITLE
Format abstract paragraphs

### PR DESCRIPTION
**Pull request by frapac**

### CODE REVIEW

**Comment by ffevotte** [comment]
Looks good! Would you like me to merge?

On a related note, I originally shortened my abstract so that it does not take too much space. I'm not very happy with the result, and the new styling with a smaller font for abstracts makes me wonder if I could/should give a bit more details.

Do you have an opinion on this?

**Comment by frapac** [comment]
I think providing more details is a good idea. The clearer, the better!

**Comment by frapac** [comment]
Thinking about it, I think we could add more generic information about Julia's events in Paris. I heard that Michael is planning to organize a Julia event at Jussieu. And you sent an email earlier about a formation in Julia that will be organize by Triscale Innov.

**Comment by ffevotte** [comment]
Yes, I'm all for advertising Julia events in Paris (and especially TriScale's training sessions ;-)), but wouldn't that directly conflict with http://juliafran.org/? Maybe we should instead list such events there, and link to juliafran from julia-users-paris...

That being said, it looks like the objective of JuliaFran is to host a French-speaking community, whereas julia-users-paris could have a different audience, both broader in terms of language, and narrower in terms of geographical extent. So, all in all, that could indeed be a good idea !

How would you present such info? In a separate page? Or maybe interspersed in chronological order within the list of meetups?

**Pull request merged**
