### PR TITLE
Sponsors

### PR DESCRIPTION
**Pull request by ffevotte**
@frapac does that look like what you had in mind regarding listing event sponsors in the web page?

### CODE REVIEW

**Comment by frapac** [comment]
That's exactly that I have in mind! A short question: should we put the sponsors at the top of the page or at the bottom?

**Comment by mfherbst** [comment]
My intuition is to go for the bottom of the page, but I'm fine with the current version, too.

**Comment by ffevotte** [comment]
> My intuition is to go for the bottom of the page, but I'm fine with the current version, too.

I just pushed an alternate proposal in #6, where the list of sponsors goes to the bottom of the page.

**Comment by frapac** [comment]
I am more in favor of putting the sponsor at the bottom, but I am open to the discussion. I think we could reach consensus on that point :)

**Comment by ffevotte** [comment]
I'm very fine with the version where the sponsors list is displayed at the bottom of the page. And I'm also very fine with the current version, where the sponsors list is not displayed at all.

So please do what you feel is best: merge #5 or #6, or neither. From the discussion on this PR and the e-mail thread, it is clear enough that #5 is not the preferred option. I think this leaves with a choice between #6 or nothing.

But there might be other options, like only mentioning QuantStack (because they provide the venue) but not TriScale (because we did not do much besides volunteering some time, like everybody else did)...

**Comment by frapac** [comment]
@ffevotte Thanks for this update! So, let's merge PR#6 . However, I am in favor of putting TriScale, as:

- yes, you did volunteering, and that greatly help!
- TriScale is not a large structure, and its subject are quite related to Julia
- and at some point, you may want to host a meet-up (e.g. if we pursue the idea of organizing a meet-up next to the PGMO days :) )

**Comment by mfherbst** [comment]
With #6 merged, this can be closed.

**Pull request closed without merging**
